import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:kelal_studio/core/theme/app_colors.dart';
import 'package:kelal_studio/core/theme/app_spacing.dart';
import 'package:kelal_studio/core/theme/app_typography.dart';

class LegalPage extends StatelessWidget {
  const LegalPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: context.colors.bgCanvas,
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.symmetric(
            horizontal: AppSpacing.xl,
            vertical: AppSpacing.lg,
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              GestureDetector(
                onTap: () => context.pop(),
                child: Padding(
                  padding: const EdgeInsets.symmetric(vertical: AppSpacing.sm),
                  child: Text(
                    '← Back',
                    style: AppTypography.bodySmall.copyWith(
                      color: context.colors.textSecondary,
                    ),
                  ),
                ),
              ),
              const SizedBox(height: AppSpacing.md),
              Text(
                'Legal',
                style: AppTypography.display.copyWith(
                  color: context.colors.textPrimary,
                ),
              ),
              const SizedBox(height: AppSpacing.xxl),
              _buildListItem(context, 'Privacy Policy'),
              Divider(color: context.colors.borderSubtle, height: 1),
              _buildListItem(context, 'Terms of Service'),
              Divider(color: context.colors.borderSubtle, height: 1),
              _buildListItem(context, 'Content Ownership'),
              Divider(color: context.colors.borderSubtle, height: 1),
              _buildListItem(context, 'Third-Party Font Licenses'),
              const SizedBox(height: AppSpacing.lg),
              Container(
                width: double.infinity,
                padding: const EdgeInsets.all(AppSpacing.lg),
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Text(
                  'Noto Sans Ethiopic is licensed under the SIL Open Font '
                  'License, version 1.1.',
                  style: AppTypography.caption.copyWith(
                    color: context.colors.textSecondary,
                    height: 1.5,
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildListItem(BuildContext context, String title) {
    var content = '';
    if (title == 'Privacy Policy') {
      content =
          'Kelal Studio operates as a supervised public beta.\n\n'
          'Per PRD Section 7.9, we are evaluating whether selected AI '
          'providers train on submitted prompts. User prompts (e.g., "50% '
          'off starting Friday") are considered competitively sensitive.\n\n'
          'Kelal Studio enforces per-user quotas locally and logs '
          'moderation rejections for review. All data is managed according '
          'to Ethiopian data-protection laws, pending further legal '
          'residency review.';
    } else if (title == 'Terms of Service') {
      content =
          'Kelal Studio is an automated social-media content engine for '
          'Ethiopian businesses.\n\n'
          'By using Kelal Studio, you agree to our quota limits (e.g., '
          'daily generation ceilings) and moderation policies. Provider '
          'rate limits are enforced globally per account.\n\n'
          'We do not support direct Meta/TikTok API auto-posting; '
          'distribution is handled manually via the native OS Share Sheet. '
          'We do not provide a manual timeline video editor.';
    } else if (title == 'Content Ownership') {
      content =
          'As an Ethiopian business owner using Kelal Studio, the output '
          'generated by our Multi-Format Asset Generation Pipeline belongs '
          'to you, pending confirmation of provider terms .\n\n'
          'Unlicensed video background audio is explicitly out of scope '
          'for our teasers to protect you from platform audio-matching '
          'strikes.';
    } else if (title == 'Third-Party Font Licenses') {
      content =
          'Noto Sans Ethiopic\n\n'
          'SIL OPEN FONT LICENSE Version 1.1 - 26 February 2007\n\n'
          'PREAMBLE\n'
          'The goals of the Open Font License (OFL) are to stimulate '
          'worldwide development of collaborative font projects...';
    }

    return InkWell(
      onTap: () {
        context.push(
          '/settings/legal_document',
          extra: {'title': title, 'content': content},
        );
      },
      child: Padding(
        padding: const EdgeInsets.symmetric(vertical: AppSpacing.xl),
        child: Row(
          children: [
            Expanded(
              child: Text(
                title,
                style: AppTypography.body.copyWith(
                  color: context.colors.textPrimary,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
